fields:
  id:
    label: ID
    position: '1'
    type: label
    foreign_key: '0'
    options:
      visible: '1'
      disabled : '0'
      readonly: '1'
  name:
    label: Name
    position: '3'
    type: text
    foreign_key: '0'
    options:
      visible: '1'
      disabled : '0'
      readonly: '0'
  university_id:
    label: University
    position: '2'
    type: select
    foreign_key: '1'
    display_field : 'abbr'
    options:
      visible: '1'
      disabled : '0'
      readonly: '1'

buttons:
  save :
    label : Save
  back:
    label : Back

actions:
  edit: 1
  view : 1
  delete : 1
  save : 1
  add: 1

relations:
  university:
    label: 'University'
    type: 'belongs_to'
    visible: 1
