label : 
  label : 'Название'
  type : 'text'
  options:
position :
  label : 'Позиция'
  type : 'text'
  options:
type : 
  label : 'Тип'
  type : 'select'
  options:
    values : 'field_types'
foreign_key:
  label : 'Внешний ключ'
  type: 'select'
  options:
    values : 'yes_no'
display_field:
  label : 'Поле внешнего ключа'
  type: 'select'
  options:
    values : 'model_fields'
options:
  visible :
    label : 'Visible'
    type : 'select'
    options:
      values : 'yes_no'
  readonly :
    label : 'Readonly'
    type : 'select'
    options:
      values : 'yes_no'
  disabled :
    label : 'Disabled'
    type : 'select'
    options:
      values : 'yes_no'